cargo-features = ["codegen-backend"]
[package]
name = "n_minesweeper"
version = "0.2.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.1", features = ["wayland"] }
rand = "0.8.5"

[profile.dev]
debug = 0
codegen-backend = "cranelift"

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
