cargo-features = ["codegen-backend"]
[package]
name = "n_minesweeper"
version = "0.4.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2", default-features = false, features = [
    "wayland",
    "x11",
    "bevy_winit",
    "bevy_asset",
    "bevy_text",
    "bevy_ui",
    "bevy_render",
    "bevy_sprite",
    "default_font"
] }
rand = "0.8.5"

[profile.dev]
debug = 0
codegen-backend = "cranelift"

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
