name: build

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: N Mines
  PROJECT_PATH: n_mines

jobs:
  build-win:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -v -p build/win
          godot --headless --verbose --export-release "Windows Desktop" "build/win/NMines.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: win
          path: build/win
      - name: Zip files
        uses: vimtor/action-zip@v1.2
        with:
          files: build/win/NMines.exe
          dest: "N Mines Windows.zip"
      - name: Publish in release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            N Mines Windows.zip

            
  build-mac:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -v -p build/mac
          godot --headless --verbose --export-release "macOS" "build/mac/N.Mines.Mac.zip"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac
          path: build/mac
      - name: Publish in release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            N.Mines.Mac.zip

            
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -v -p build/linux
          godot --headless --verbose --export-release "Linux" "build/linux/NMines.x86_64"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: build/linux
      - name: Zip files
        uses: vimtor/action-zip@v1.2
        with:
          files: build/linux/NMines.x86_64
          dest: "N Mines Linux.zip"
      - name: Publish in release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            N Mines Linux.zip

            
  build-android:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          echo ${{secrets.SECRET_RELEASE_KEYSTORE_BASE64}} | base64 --decode > /root/release.keystore
          mkdir -v -p build/android
          sed 's@keystore/release=".*"@keystore/release="'/root/release.keystore'"@g' -i export_presets.cfg
          sed 's@keystore/release_user=".*"@keystore/release_user="'${{secrets.SECRET_RELEASE_KEYSTORE_USER}}'"@g' -i export_presets.cfg
          sed 's@keystore/release_password=".*"@keystore/release_password="'${{secrets.SECRET_RELEASE_KEYSTORE_PASSWORD}}'"@g' -i export_presets.cfg
          godot --headless --verbose --export-release "Android" "build/linux/NMines.apk"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: build/android
      - name: Zip files
        uses: vimtor/action-zip@v1.2
        with:
          files: build/ndroid/NMines.apk
          dest: "N Mines Android.zip"
      - name: Publish in release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            N Mines Android.zip
