name: build

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: N Mines
  PROJECT_PATH: n_mines

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          godot --headless --verbose --export-release "Linux" "build/linux/N Mines.x86_64"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: build/linux
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1.2
        with:
          files: "build/linux/N Mines.x86_64"
          dest: "N Mines Linux.zip"
      - name: Publish in release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            N Mines Linux.zip
